= Chaos Indicators of Compromise

Below are our indicators of compromise for the `sebd/chaos` analysis we
performed.

// TODO
// link to blog post once out

== File hashes

* Chaos:
  https://www.virustotal.com/#/file/e9fc1441bb88dd8cc7fcc2e176e53084ccd28f8766a017b3a07474b7e6b72ab9/details[0a27b0579702888c3399c6b853acf986beae2a4e]
* Client:
  https://www.virustotal.com/#/file/9fbdbf80e3d7482e8d9781c4f9cf423ec50d434b324658835653c40101de9368/detection[7f5d3bb5079f9bf077832301615fa6e2e072c4e8]


== File system

WARNING: The filesystem artifacts documented below are also *legitimate system
files*. You need to investigate a little bit before jumping to conclusions.

This group installs the backdoor in `/usr/sbin/smdb` and a puts a backup of it
in `/usr/include/stabd.h`.

`/usr/sbin/smdb` when legitimate is part of the Samba suite. Installed for
Windows compatibility like file-sharing or Active Directory integration.

`/usr/include/stabd.h` when legitimate is part of the glibc header files. It
is a plain text file. When malicious it is a binary file.

You can inspect the files manually or run our Yara rule against them with:

    yara sedb_chaos.yar /usr/sbin/smdb
    yara sedb_chaos.yar /usr/include/stabd.h

`/etc/init.d/runlevels` when malicious is a script that will open ports on the
firewall and execute the backdoor. Its the malware's persistence mechanism.

== System investigation

Listening raw sockets are a very rare thing on normal Linux servers. You can
inspect your system by running the below command as root:

    netstat -lwp

This will list the processes which have listening raw sockets open. You can
then investigate processes to assess if it is legitimate or not. If you (or
your system administrator) doesn't know what it is, it is likely not
legitimate since listening raw sockets are rare.

== If you are infected

Because chaos doesn't come alone but with at least one IRC Bot that has remote
code execution capabilities, we advise infected hosts to be fully reinstalled
from a trusted backup.
